<!doctype html>
<html lang = "es">
<head>
    <meta charset = "UTF-8">
    <meta name = "viewport" content = "width=device-width, user-scalable=no, initial-scale=0.8, maximum-scale=0.8, minimum-scale=0.8">
    <meta http-equiv = "X-UA-Compatible" content = "ie=edge">

    <title>Ingreso de Usuarios</title>
    <link rel = "stylesheet" type = "text/css" href = "<?= BASE_URL?>/plugins/fontawesome/css/all.min.css?v=5">
    <link rel = "stylesheet" type = "text/css" href = "<?= BASE_URL?>/plugins/bs4/bootstrap.min.css?v=4.2">
    <link rel = "stylesheet" type = "text/css" href = "<?= BASE_URL?>/plugins/sweetalert2/sweetalert2.min.css">
    <link rel = "stylesheet" type = "text/css" href = "<?= BASE_URL?>/css/main.css">

    <style>
        html, body {
            height: 100%;
            padding: 0px;
            color: #333333;
            font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji" !important;
        }

        input{
            padding: .5rem !important;
        }
    </style>

</head>
<body>
<div id = "loading" class = "loading" style = "display: flex; right: 0">
    <div class = "w-100">
        <h2><i class = "fas fa-circle-notch fa-spin fa-lg"></i> Cargando...</h2>
    </div>
</div>
<!-- Position it -->
<div class = "position-fixed w-100 d-flex flex-column p-4" id = "alert-toast-wrapper-top" style = "z-index: 4000"></div>
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100">
        <div class = "col-md-12">
            <div class="row justify-content-center align-items-center h-100">
                <div style="width: 500px; padding: 50px;" class="border rounded shadow">
                    <div class="text-center">
                        <h1><i class="fa fa-users"></i></h1>
                        <h2>Ingreso de usuarios</h2>
                    </div>
                    <form id="login-form">

                        <div class="mt-1 form-wrapper">
                            <div class="form-group">
                                <label for="IdLogin"></label>
                                <input type="text" name="IdLogin"  id="user" class="form-control" id="" placeholder="Usuario"  autocomplete="username">
                                <div class="invalid-feedback">
                                    Seleccione un numero de dias valido
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Contrasena"></label>
                                <input type="password" name="Contrasena" id="pass" class="form-control" id="" placeholder="Ingrese su contraseña"  autocomplete="current-password">
                                <div class="invalid-feedback">
                                    Seleccione un numero de dias valido
                                </div>
                            </div>
                        </div>
                        <div class="text-center mt-4">
                            <button type="submit" id="send" href="javascript:void(0)"  class="btn btn-outline-primary  w-100" >
                                Iniciar sesión
                            </button>
                            <div class="alert-msg mt-4">

                            </div>
                        </div>
                    </form>
                  </div>
            </div>
        </div>
    </div>
</div>
<script type="application/javascript">
    var BASE_URL = "<?= BASE_URL?>";
</script>
<script src = "<?= BASE_URL?>/plugins/jquery3.4.min.js"></script>
<script src = "<?= BASE_URL?>/plugins/bs4/bootstrap.bundle.min.js?v=4.2"></script>
<script src = "<?= BASE_URL?>/plugins/mustache/jquery.mustache.js"></script>
<script src = "<?= BASE_URL?>/plugins/moment/moment.min.js"></script>
<script src = "<?= BASE_URL ?>/plugins/sweetalert2/sweetalert2.all.min.js"></script>
<script src = "<?= BASE_URL?>/js/helpers.js"></script>
<script src = "<?= BASE_URL?>/js/pages/login.js"></script>
</body>
</html>