<h1>
    Usuarios
</h1>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <button type="button" class="btn btn-outline-secondary"><i class="fa fa-plus"></i> Agregar nuevo</i></button>
    </div>
    <div class="btn-group mr-2" role="group" aria-label="Second group">

     </div>
    <div class="btn-group" role="group" aria-label="Third group">

    </div>
</div>

<div class="row my-4">
    <div class="col-12">
        <table class="table" id="tabla_usuarios">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Nombre</th>
                <th scope="col">Role</th>
                <th scope="col" class="text-right"><i class="fa fa-ellipsis-v"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($usuarios as $usuario): ?>
            <tr>
                <th scope="row"><?= $usuario->user_id?></th>
                <td><?= $usuario->username?></td>
                <td><?= $usuario->nombre?></td>
                <td><?= $usuario->role?></td>
                <td class="text-right">
                    <div class="btn-group mr-2" role="group" aria-label="First group">
                        <button type="button" class="btn btn-outline-secondary"><i class="fa fa-pen"></i> </button>
                        <button type="button" class="btn btn-outline-danger"><i class="fa fa-trash"></i></button>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script src="/js/pages/usuarios.js"></script>